### ISSUE TITLE
isMobile no longer accepts call without parameter in a TypeScript project

### ISSUE THREAD

**Issue by sebastianljunggren** [kaimallea/isMobile#129]
In 1.0.3, it was possible to call ismobile like this:

```
import isMobile from 'ismobilejs';
const result = isMobile();
```

After upgrading to 1.1.0, this will no longer compile in my Typescript setup (an Angular 9 project). The compilation error is `TS2554: Expected 1 arguments, but got 0.`.

One possible workaround is to make an explicit call with undefined:

```
import isMobile from 'ismobilejs';
const result = isMobile(undefined);
```

However, I believe the proper fix would be to add `?` to the signature of `isMobile()`.

**Comment by kaimallea** [comment]
Yes this is a big, I forgot to make it optional. Thanks for reporting! Fix incoming..

**Comment by sebastianljunggren** [comment]
Thank you for the quick handling of this!
